language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    fast_finish: true

before_script:
    - composer self-update
    - composer update

script:
    - cd $TRAVIS_BUILD_DIR
    - vendor/bin/phpunit -c test/phpunit.xml --coverage-clover=./build/clover.xml
    - vendor/bin/phpcs --standard=PSR2 -s -p src/

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml
