name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: sudo apt-get -y install emscripten cmake
      - run: mkdir build
      - run: emcmake cmake -B build . -DCMAKE_BUILD_TYPE=Release
      - run: emmake make -C build
      - run: cp build/dfmapcompressorpp.js web/
      - run: cp build/dfmapcompressorpp.wasm web/
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
